# Generated by Django 5.0.6 on 2025-02-09 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_rename_time_event_start_time_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsender',
            name='specified_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
