# Generated by Django 5.0.6 on 2025-02-11 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_rename_title_event_name_event_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsender',
            name='specified_time',
        ),
        migrations.AddField(
            model_name='emailsender',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
