# Generated by Django 5.0.6 on 2025-02-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_remove_emailsender_specified_time_emailsender_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emailsender',
            name='date',
        ),
    ]
