# Generated by Django 3.2.12 on 2025-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_day_checker_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone_number',
            field=models.IntegerField(default='6948947751', max_length=12),
        ),
    ]
