# Generated by Django 3.2.12 on 2025-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_event_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.IntegerField(default='6948947751'),
        ),
    ]
