# Generated by Django 3.2.12 on 2025-02-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_alter_event_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sent_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
