# Generated by Django 5.0.6 on 2025-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_emailsender_specified_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='nikoloupaul@gmail.com', max_length=254),
        ),
    ]
